### ISSUE TITLE
Question on how to databind using model driven forms

### ISSUE THREAD

**Issue by RedFour** [DeborahK/ngconf2016#4]
Hi Deborah,

I'm trying out the new model driven forms but I've been having a hard time getting data binding to work. I'm using RC5 and ReactiveFormsModule. I have some template driven forms that I'm converting to model driven forms.

It is possible to have 2-way data binding between a FormControl and a variable, without using ngModel?

The code below will make the form initialize with testString's value. But form.value.firstName and testString are not bound together.

```
  form: FormGroup;
  testString: string = "abc test";

  constructor(private fb: FormBuilder) {
      this.form = this.fb.group({
            firstName: [this.testString]
      });
  }
```

**Comment by DeborahK** [comment]
When moving to model-driven (now called "Reactive Forms") there is no data binding. As you probably saw, as soon as you use ReactiveFormsModule instead of FormsModule, there is no ngModel.

If you need data binding, stick with template-driven forms. If you want full control of a form then use reactive forms.

Note, though, that you can see the values of the input elements using the `this.form.value` property.

Hope this helps.

**Comment by RedFour** [comment]
Thank you.
